# Generated by Django 3.1.7 on 2021-04-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_category', models.CharField(choices=[('kr', 'krajowa'), ('zg', 'zagraniczna')], max_length=15)),
                ('application_status', models.CharField(choices=[('saved', 'Zapisany'), ('in_progress', 'W akceptacji'), ('approoved', 'Zaakcdptowany'), ('settled', 'Rozliczony'), ('canceled', 'Anulowany')], max_length=30)),
                ('employee_level', models.CharField(choices=[('lvl1', 'podstawowy'), ('lvl2', 'kierownik'), ('lvl3', 'dyrektor'), ('lvl4', 'dyrektor regionu'), ('lvl5', 'dyrektor dywizji'), ('lvl6', 'członek zarządu'), ('lvl7', 'prezes zarządu')], max_length=30)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('trip_purpose_text', models.CharField(max_length=250)),
                ('transport_type', models.CharField(choices=[('train', 'pociąg'), ('plane', 'samolot'), ('company_car', 'samochód służbowy'), ('own_car', 'własny samochód'), ('other', 'inny')], max_length=30)),
                ('travel_route', models.CharField(max_length=120)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlementCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_cost_category', models.CharField(choices=[('accommodation', 'nocleg'), ('transport', 'dojazd'), ('luggage', 'bagaż'), ('other', 'inne')], max_length=40)),
                ('bt_cost_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bt_cost_document_date', models.DateField()),
                ('bt_cost_VAT_rate', models.CharField(choices=[('W1', '23 %'), ('W8', '8 %'), ('WN', 'nie dotyczy'), ('W0', 'zwolniony')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlementFeeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_quantity', models.IntegerField()),
                ('dinner_quantity', models.IntegerField()),
                ('supper_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_completed', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=25)),
                ('bt_start_date', models.DateField()),
                ('bt_start_time', models.TimeField()),
                ('bt_end_date', models.DateField()),
                ('bt_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BtSubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlementMileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_car_reg_number', models.CharField(max_length=8)),
                ('trip_start_place', models.CharField(max_length=50)),
                ('trip_date', models.DateField()),
                ('trip_description', models.CharField(max_length=120)),
                ('trip_purpose', models.CharField(max_length=240)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bt_application_settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bt_application_settlement_mileages', to='e_delegacje.btapplicationsettlement')),
            ],
        ),
    ]
