# Generated by Django 3.1.7 on 2021-04-05 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_delegacje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btdepartment',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bt_Departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
