# Generated by Django 3.1.7 on 2021-04-11 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btuser',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bt_Users', to='e_delegacje.btlocation'),
            preserve_default=False,
        ),
    ]
