# Generated by Django 3.1.7 on 2021-04-10 12:27

from django.db import migrations, models
import django.db.models.deletion
import e_delegacje.enums


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0002_auto_20210410_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bt_Users', to='e_delegacje.btdepartment'),
        ),
        migrations.AlterField(
            model_name='btuser',
            name='employee_level',
            field=models.CharField(choices=[('lvl1', 'podstawowy'), ('lvl2', 'kierownik'), ('lvl3', 'dyrektor'), ('lvl4', 'dyrektor regionu'), ('lvl5', 'dyrektor dywizji'), ('lvl6', 'członek zarządu'), ('lvl7', 'prezes zarządu')], default=e_delegacje.enums.BtEmployeeLevel['lvl7'], max_length=15),
        ),
    ]
