# Generated by Django 3.1.7 on 2021-04-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0003_auto_20210411_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplication',
            name='trip_category',
            field=models.CharField(choices=[('krajowa', 'Kr'), ('zagraniczna', 'Zg')], max_length=15),
        ),
    ]
