# Generated by Django 3.1.7 on 2021-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0003_auto_20210405_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btuser',
            name='employee_level',
            field=models.CharField(choices=[('lvl1', 'podstawowy'), ('lvl2', 'kierownik'), ('lvl3', 'dyrektor'), ('lvl4', 'dyrektor regionu'), ('lvl5', 'dyrektor dywizji'), ('lvl6', 'członek zarządu'), ('lvl7', 'prezes zarządu')], max_length=15),
        ),
    ]
