# Generated by Django 3.1.7 on 2021-04-05 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_delegacje', '0004_auto_20210405_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btuser',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
