# Generated by Django 3.1.7 on 2021-04-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0004_auto_20210411_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplication',
            name='trip_category',
            field=models.CharField(choices=[('kr', 'krajowa'), ('zg', 'zagraniczna')], max_length=15),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlement',
            name='bt_application_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bt_applications_settlements', to='e_delegacje.btapplication'),
        ),
    ]
