# Generated by Django 3.1.7 on 2021-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0005_auto_20210411_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplication',
            name='application_status',
            field=models.CharField(choices=[('saved', 'Zapisany'), ('in_progress', 'W akceptacji'), ('approoved', 'Zaakcdptowany'), ('settled', 'Rozliczony'), ('canceled', 'Anulowany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlementcost',
            name='bt_cost_VAT_rate',
            field=models.CharField(choices=[('W1', '23 %'), ('W8', '8 %'), ('WN', 'nie dotyczy'), ('W0', 'zwolniony')], max_length=10),
        ),
        migrations.AlterField(
            model_name='btmileagerates',
            name='vehicle_type',
            field=models.CharField(choices=[('car_under_900cm3', 'auto o pojemności do 900cm3'), ('car_above_900cm3', 'auto o pojemności powyżej 900cm3'), ('motorbike', 'motocykl'), ('moped', 'motorower')], max_length=20),
        ),
    ]
