# Generated by Django 3.1.7 on 2021-04-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0006_auto_20210411_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btuser',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bt_Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
