# Generated by Django 3.1.7 on 2021-04-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0002_auto_20210411_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplicationsettlementinfo',
            name='bt_application_settlement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bt_application_info', to='e_delegacje.btapplicationsettlement'),
        ),
    ]
