# Generated by Django 3.1.7 on 2021-04-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0010_btcurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btapplicationsettlementcost',
            name='attachment',
        ),
        migrations.AddField(
            model_name='btapplicationsettlementcost',
            name='bt_cost_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bt_application_settlement_costs', to='e_delegacje.btcurrency'),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlementcost',
            name='bt_cost_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_application_settlement_costs', to='e_delegacje.btcurrency'),
        ),
    ]
