# Generated by Django 3.1.7 on 2021-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0011_auto_20210412_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='btapplicationsettlementcost',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
