# Generated by Django 3.1.7 on 2021-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0013_btapplicationsettlementcost_bt_cost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplicationsettlementcost',
            name='bt_cost_category',
            field=models.CharField(choices=[('nocleg', 'nocleg'), ('dojazd', 'dojazd'), ('bagaż', 'bagaż'), ('inne', 'inne')], max_length=40),
        ),
    ]
