# Generated by Django 3.1.7 on 2021-04-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0015_auto_20210414_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btapplicationsettlementmileage',
            old_name='bt_milage_rate',
            new_name='bt_mileage_rate',
        ),
    ]
