# Generated by Django 3.1.7 on 2021-04-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20210416_2334'),
        ('e_delegacje', '0017_auto_20210416_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btapplication',
            name='trip_category',
        ),
        migrations.AddField(
            model_name='btapplication',
            name='application_log',
            field=models.CharField(default='', max_length=2400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btapplication',
            name='bt_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications', to='setup.btcountry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btapplicationsettlementinfo',
            name='settlement_log',
            field=models.CharField(default='', max_length=2400),
            preserve_default=False,
        ),
    ]
