# Generated by Django 3.1.7 on 2021-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0018_auto_20210417_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplication',
            name='transport_type',
            field=models.CharField(choices=[('default', ''), ('train', 'pociąg'), ('plane', 'samolot'), ('company_car', 'samochód służbowy'), ('own_car', 'własny samochód'), ('other', 'inny')], max_length=30),
        ),
    ]
