# Generated by Django 3.1.7 on 2021-04-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20210416_2334'),
        ('e_delegacje', '0019_auto_20210417_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='btapplication',
            name='advance_payment_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications', to='setup.btcurrency'),
            preserve_default=False,
        ),
    ]
