# Generated by Django 3.1.7 on 2021-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0020_btapplication_advance_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='btapplicationsettlementinfo',
            name='settlement_exchange_rate',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='btapplication',
            name='application_status',
            field=models.CharField(choices=[('saved', 'Zapisany'), ('in_progress', 'W akceptacji'), ('approved', 'Zaakceptowany'), ('settlement_in_progress', 'Rozliczany'), ('settled', 'Rozliczony'), ('canceled', 'Anulowany')], max_length=30),
        ),
    ]
