# Generated by Django 3.1.7 on 2021-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0022_auto_20210428_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplication',
            name='application_status',
            field=models.CharField(choices=[('saved', 'Zapisany'), ('in_progress', 'W akceptacji'), ('approved', 'Zaakceptowany'), ('rejected', 'Odrzucony'), ('settlement_in_progress', 'W rozliczeniu'), ('settled', 'Rozliczony'), ('canceled', 'Anulowany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlement',
            name='settlement_status',
            field=models.CharField(choices=[('saved', 'Zapisany'), ('in_progress', 'W akceptacji'), ('approved', 'Zaakceptowany'), ('rejected', 'Odrzucony'), ('settlement_in_progress', 'W rozliczeniu'), ('settled', 'Rozliczony'), ('canceled', 'Anulowany')], max_length=30),
        ),
    ]
