# Generated by Django 3.1.7 on 2021-06-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20210417_1431'),
        ('e_delegacje', '0023_auto_20210430_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplication',
            name='advance_payment_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications', to='setup.btcurrency'),
        ),
        migrations.AlterField(
            model_name='btapplication',
            name='application_status',
            field=models.CharField(choices=[('saved', 'zapisany'), ('in_progress', 'w akceptacji'), ('approved', 'zaakceptowany'), ('rejected', 'odrzucony'), ('settlement_in_progress', 'W rozliczeniu'), ('settled', 'rozliczony'), ('canceled', 'anulowany')], max_length=30),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlement',
            name='settlement_status',
            field=models.CharField(choices=[('saved', 'zapisany'), ('in_progress', 'w akceptacji'), ('approved', 'zaakceptowany'), ('rejected', 'odrzucony'), ('settlement_in_progress', 'W rozliczeniu'), ('settled', 'rozliczony'), ('canceled', 'anulowany')], max_length=30),
        ),
    ]
