# Generated by Django 3.1.7 on 2021-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0024_auto_20210601_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='btapplication',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='btapplication',
            name='approver',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
