# Generated by Django 3.1.7 on 2021-06-09 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_delegacje', '0025_auto_20210609_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplication',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bt_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
