# Generated by Django 3.1.7 on 2021-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0027_auto_20210611_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplicationsettlementinfo',
            name='bt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlementinfo',
            name='bt_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlementinfo',
            name='bt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlementinfo',
            name='bt_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btapplicationsettlementinfo',
            name='settlement_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
