# Generated by Django 3.1.7 on 2021-07-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0028_auto_20210617_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='btapplicationsettlementmileage',
            name='is_agreement_signed',
            field=models.BooleanField(default=False),
        ),
    ]
