# Generated by Django 3.1.7 on 2021-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20210411_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('text', models.CharField(max_length=10)),
            ],
        ),
    ]
