# Generated by Django 3.1.7 on 2021-04-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_btcurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
                ('alpha_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BtDelegationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delagation_rate', models.IntegerField()),
                ('alpha_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bt_Delegation', to='setup.btcountry')),
            ],
        ),
        migrations.DeleteModel(
            name='BtRatesTax',
        ),
    ]
