# Generated by Django 3.1.7 on 2021-04-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20210416_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btdelegationrate',
            old_name='alpha_code',
            new_name='country',
        ),
    ]
